package org.cryptoBros.presentation.Enum;

public enum ButtonEnumeration {
    SIGNUP,
    LOGIN,
    CONFIRM_SIGNUP,
    CONFIRM_LOGIN,
	SETTINGS,
	PORTFOLIO,
    LOGOUT,
    DELETE,
    HOME,
	MANAGE_CRYPTO,
    CONFIRM_BALANCE,
    ADD_CRYPTO,
	BACK,
    CONFIRM,
	PROFILE,
	CHANGE_PASSWORD,
	CHANGE_USERNAME,
	CHANGE_PROFILE_PIC,
	EDIT_CRYPTO
}
